---
title: "Johns Hopkins' Covid-19 Data EDA"
author: "Cody Hill"
date: "2023-04-25"
output:
  pdf_document: default
  html_document: default
---

## Setup

Note, before using knitr please install all missing packages from the code cell below into your environment. Also, I recommended
knitting into HTML as it has been optimized for viewing in that format.

### Data Source Information

**"COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University"**
This data was procured from <https://github.com/CSSEGISandData/COVID-19> which is a github repository where Johns Hopkins compiled covid-19 data. This repository stopped updating on 3/10/23.
In this report we are specifically looking at the `./csse_covid_19_data/csse_covid_19_time_series` data.

I encourage all who reads this report to go read the `readme.md` file in the source's repository to gain more insights about where this data was collected, how it was validated, and compiled into this dataset.
In short, the US data was collected from individual state and county Departments of Health and the global data was collected from various government bodies within each country (with a few exceptions).

*This data set is licensed under the Creative Commons Attribution 4.0 International (CC BY 4.0) by the Johns Hopkins University on behalf of its Center for Systems Science in Engineering. Copyright Johns Hopkins University 2020.*

#### Feature Descriptions from Source

**FIPS:** US only. Federal Information Processing Standards code that uniquely identifies counties within the USA.
**Admin2:** County name. US only.
**Province_State:** Province, state or dependency name.
**Country_Region:** Country, region or sovereignty name. The names of locations included on the Website correspond with the official designations used by the U.S. Department of State.
**Lat and Long_:** Dot locations on the dashboard. All points (except for Australia) shown on the map are based on geographic centroids, and are not representative of a specific address, building or any location at a spatial scale finer than a province/state. Australian dots are located at the centroid of the largest city in each state.
**Confirmed:** Counts include confirmed and probable (where reported).
**Deaths:** Counts include confirmed and probable (where reported).
**UID:** Unique Identifier for each row entry.
**ISO3:** Officially assigned country code identifiers.

### Environment Setup

First we will import the libraries in R that are needed.

Then, we will import the data using a URL directly from the source, this means it will update anytime we reknit.

```{r Setup RMD}
# Output all commands run and set a standard plot size
knitr::opts_chunk$set(echo = TRUE, fig.width = 10, fig.height = 6)
# Import Libraries
library(tidyverse)
library(lubridate)
library(ggplot2)
library(ggmap)
library(gridExtra)
# Import dataset
us_cases <- read.csv("https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv")
us_deaths <- read.csv("https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv")
global_cases <- read.csv("https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
global_deaths <- read.csv("https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")
```